---
- hosts: all
  tasks:
  - name: Set a hostname
    hostname:
      name: mailserver10
  - name: Add an Ethernet connection with static IP configuration
    nmcli:
      conn_name: eth0
      ifname: eth0
      type: ethernet
      ip4: 192.168.122.150/24
      gw4: 192.168.122.1
      state: present
      autoconnect: yes
