---
- hosts: all
  tasks:
  - name: Set a hostname
    hostname:
      name: mailserver
  - name: Add an Ethernet connection with static IP configuration
    nmcli:
      conn_name: eth0
      ifname: eth0
      type: ethernet
      ip4: 192.168.122.150/24
      gw4: 192.168.122.1
      state: present
      autoconnect: yes
  - name: Copy from Local to Remote Target Machine with 'copy'
    copy:
      src: local_dns
      dest: /etc/hosts
      backup: yes

  - name: Install a list of packages with a list variable
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - vim
        - net-tools
        - bash-completion
        - bash-completion-extras
  - name: Return motd to registered var
    command: source /etc/profile.d/bash_completion.sh
    register: mymotd
